config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  root "pages#home"
  resources :posts
  
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registration#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true

	has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], per_page: 12)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer class="text-center text-white">
  <div class="container pt-4">
    <section class="mb-4">
      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark">
				<i class="fa-brands fa-instagram"></i>
			</a>
			<a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark">
				<i class="fa-brands fa-linkedin"></i>
			</a>
			<a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark">
				<i class="fa-brands fa-github"></i>
			</a>
    </section>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-light">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Gallery', posts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About Me', pages_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', pages_contact_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'New Post', new_post_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mel Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= render 'layouts/footer' %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>I am a cat lover, and I love to run, sorry I'm just thinking about cats again, I can't hug every cat.</p>

app/views/pages/contact.html.erb
<h1>Contact Me</h1>
<p>HMU for a good time, not a long time</p>

app/views/pages/home.html.erb
<h1>Mel's Portfolio</h1>
<p>Check out this great site that is all about me because I'm SOOO important</p>

app/views/posts/_form.html.erb
<div class="col-xl-4 col-md-6 col-sm-8 col-10">
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.file_field :images, multiple: true %>
    </div>

    <div>
      <%= form.submit class: 'btn btn-primary col-12' %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <% post.images.each do |image| %>
    <%= image_tag(image) %>
  <% end %>

  <p class="post_title"><%= link_to post.title, post %></p>
  <p class="post_desc"><%= post.description %></p>
  <p class="date"><%= post.created_at.strftime("%A, %B %d") %></p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Gallery</h1>

<div id="posts">
  <% if @posts.count.zero? %>
    <p>No posts to show at this time.</p>
  <% end %>

  <% @posts.each do |post| %>
    <div class="gallery_post">
      <div id="<%= dom_id post %>">
        <%= image_tag(post.images.first) %>
        <p class="gallery_post_title"><%= link_to post.title, post %></p>
        <p class="gallery_post_desc"><%= post.description %></p>
        <p class="gallery_post_date"><%= post.created_at.strftime("%A, %B %d") %></p>
      </div>
    </div>
  <% end %>

  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<div class="row">
  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<div id="<%= dom_id @post %>" class="show_post">
  <h1 class="post_title"><%= @post.title %></h1>
  <p class="post_desc"><%= @post.description %></p>
  <p class="post_date"><%= @post.created_at.strftime("%A, %B %d") %></p>

  <% if user_signed_in? %>
    <div class="admin_control">
      <%= link_to "Edit", edit_post_path(@post) %>
      <%= link_to "Delete", @post, data: { turbo_method: :delete, turbo_confirm: "Delete this fr fr?" } %>
    </div>
  <% end %>

  <div class="post_gallery">
    <% @post.images.each do |image| %>
      <%= image_tag(image) %>
    <% end %>
  </div>
</div>